# permissions for end users to view guest1s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guest1-viewer-role
rules:
- apiGroups:
  - test1.example.org
  resources:
  - guest1s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test1.example.org
  resources:
  - guest1s/status
  verbs:
  - get
